name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t sebastiannegoro/react-test -f Dockerfile.dev
      - run: docker run -e CI=true sebastiannegoro/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git'

      - name: Deploy to UB
        uses: sebastiannegoro/ub-deploy@v18
        with:
          application_name: docker-gh
          environment_name: Dockergh-env
          existing_bucket_name: ub-us-east-1-8915
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip